### ISSUE TITLE
是否可以支持直接传入代码获取schema-json

### ISSUE THREAD

**Issue by keepsaunter** [yunke-yunfly/typescript-to-jsonschema#22]
目前好像只能支持 genTypeSchema.genJsonDataFormFile(file, ast)的方式传入文件地址或ast；
是否可支持类似 genJsonDataFormSource('export type A = string') 的方式

**Comment by wangweianger** [comment]
@keepsaunter 
你好 这边可以支持的 最近几天会进行支持

**Comment by wangweianger** [comment]
@keepsaunter 
已支持，请参考使用文档
